wbstack/api

composer.lock
Bump laravel/cashier from 13.3.0 to 13.4.1 
Bump phpunit/phpunit from 9.5.6 to 9.5.7 
Bump laravel/framework from 8.50.0 to 8.51.0
=> Combined PR for prefix: dependabot (21 July 2021)

.github/workflows/docker.build.yml, .github/workflows/github.prs.combine.yml
#165 Bump crazy-max/ghaction-docker-meta from 3.4.1 to 3.5.0
#164 Bump docker/build-push-action from 2.6.1 to 2.7.0
#163 Bump actions/github-script from 4.0.2 to 4.1
=> Combined PR for prefix: dependabot/github_actions

composer.lock
#160 Bump laravel/cashier from 13.4.1 to 13.4.4
#159 Bump laravel/framework from 8.52.0 to 8.55.0
=> Combined PR for prefix: dependabot/composer/laravel

composer.lock
#153 Bump vimeo/psalm from 4.8.1 to 4.9.3
#143 Bump phpunit/phpunit from 9.5.7 to 9.5.8
#139 Bump psalm/plugin-laravel from 1.4.7 to 1.5.1
#138 Bump intervention/image from 2.6.0 to 2.6.1
=> Combined PR for prefix: dependabot/composer

app/Http/Curl/CurlRequest.php, app/Http/Curl/HttpRequest.php
Abstract curl requests to an interface for DI
=> [FIRST] Add CurlRequest + HttpRequest inteface

app/Http/Curl/CurlRequest.php, app/Http/Curl/HttpRequest.php, docker-compose.integration.yml
Adds a docker-compose.integration.yml file for the api setup that can be run in CI
=> [SECOND] Add integration setup

Dockerfile
#176 Bump phpunit/phpunit from 9.5.8 to 9.5.9
#175 Bump laravel/framework from 8.55.0 to 8.58.0
#174 Bump laravel/cashier from 13.4.4 to 13.5.0
#171 Bump hadolint/hadolint-action from 1.5.0 to 1.6.0
=> Combined PR for prefix: dependabot

app/Jobs/MediawikiInit.php, tests/Jobs/MediawikiInitTest.php
- Adds check for response being an array
- Adds test for that case
=> Start using HttpRequest in MediaWikiInit

app/Console/Commands/Wiki/Delete.php, tests/Commands/Wiki/DeleteTest.php
=> Add artisan command to soft delete a wiki

docs/invitation-codes.md
https://phabricator.wikimedia.org/T297216
=> Add docs about invitation codes

.github/dependabot.yml, app/User.php, composer.json, composer.lock, config/app.php
Cashier was added many moons ago when there was some idea
of taking payment for these things
It doesnt look like that is on the horizon right now, at
least not using this library, so get rid of it!
=> Remove laravel/cashier

database/factories/InvitationFactory.php, database/factories/WikiDbFactory.php, database/factories/WikiFactory.php, database/factories/WikiManagerFactory.php
Faker was generating the same "random" values causing database constraints to fail
=> Make the faker generator more unique in factories

composer.json, composer.lock
This reverts commit fce76f2b112cbbfe4a9e369c27ab4c1f00d593f4.
This also reverts adding socket-php as a direct dependency
=> Revert "Bump maclof/kubernetes-client from 0.21.0 to 0.23.0 (#288)"

resources/views/vendor/mail/html/message.blade.php, resources/views/vendor/mail/text/message.blade.php
This also does the same to the text-only mail.
=> Capitalize and hardcode contact link

app/Jobs/PlatformStatsSummaryJob.php, app/Notifications/PlatformStatsSummaryNotification.php, config/wbstack.php, tests/Jobs/PlatformStatsSummaryJobTest.php
based on https://github.com/wbstack/api/pull/447
Pages, users, edits are a part of the query and result set but currently isn't working correctly https://github.com/wbstack/mediawiki/issues/59
=> Add job for platform summary

app/Jobs/PlatformStatsSummaryJob.php, tests/Jobs/PlatformStatsSummaryJobTest.php
This PR adds active users count to PlatformStatsSummaryJob https://phabricator.wikimedia.org/T314128
=> Add active users to PlatformStatsSummaryJob

docs/invitation-codes.md
I knew this existed somewhere, but had to look through the code to find the exact name. Probably makes sense to put it into that doc too.
=> docs: add instructions for bulk creating invite codes

app/Http/Controllers/Auth/ForgotPasswordController.php, tests/Routes/User/ForgotPasswordTest.php
Ticket: https://phabricator.wikimedia.org/T305932
Supersedes #523
=> Non-200 response code on trying to reset password leaks user information

CHANGELOG.md
Changelog for https://github.com/wbstack/api/pull/587
=> docs(changelog): prepare 8x.9.12 release

CHANGELOG.md, config/wbstack.php, database/mw/README.md, database/mw/cleanSql.php, database/mw/docker-compose-clean.yml, database/mw/new/mw1.39-wbs1.sql, tests/Jobs/DeleteWikiJobTest.php
Use db schemas from MediaWiki 1.39 https://github.com/wbstack/mediawiki/pull/333
=> Update database scripts to support MediaWiki 1.39

app/Jobs/CirrusSearch/CirrusSearchJob.php, app/Jobs/CirrusSearch/ElasticSearchIndexInit.php, tests/Jobs/CirrusSearch/ElasticSearchIndexInitTest.php
Also remove some trailing spaces
Bug: T333559
=> Do not disable elastic search on wikis after a failure

CHANGELOG.md
=> docs(changelog): add 8x.11.1 release

CHANGELOG.md, app/Jobs/PollForMediaWikiJobsJob.php, tests/Jobs/PollForMediaWikiJobsJobTest.php
Undoing the temporary changes from #611
=> chore(mw-jobs): reenable polling job

CHANGELOG.md, app/Jobs/DeleteWikiFinalizeJob.php, app/Jobs/ElasticSearchIndexDelete.php, config/wbstack.php, tests/Jobs/DeleteWikiFinalizeJobTest.php, tests/Jobs/ElasticSearch/ElasticSearchIndexDeleteTest.php, tests/Jobs/Integration/ElasticSearchIndexDeleteTest.php
Supersedes #602 
Ticket https://phabricator.wikimedia.org/T342607
=> feat(es): work against list of elasticsearch hosts

CHANGELOG.md, app/Http/Controllers/Backend/WikiController.php, tests/Routes/Wiki/GetWikiForDomainTest.php
Ticket: https://phabricator.wikimedia.org/T343743
=> Respond with appropriate status codes on failing wiki lookup in backend

CHANGELOG.md, app/Console/Kernel.php, app/Jobs/UpdateWikiSiteStatsJob.php, tests/Jobs/UpdateWikiSiteStatsJobTest.php
Ticket https://phabricator.wikimedia.org/T344583
=> feat(jobs): add job that populates wiki site stats

CHANGELOG.md
Includes two/three distinct merged PRs, so I want to align that this is ok before doing this release.
#646
#647
#648
=> Release 8x.24.0

CHANGELOG.md, app/Jobs/UpdateWikiSiteStatsJob.php, app/Wiki.php, app/WikiLifecycleEvents.php, app/WikiSiteStats.php, database/factories/WikiLifecycleEventsFactory.php, database/migrations/2023_09_19_094751_create_wiki_lifecycle_events_table.php, tests/Jobs/UpdateWikiSiteStatsJobTest.php
Ticket https://phabricator.wikimedia.org/T345434
=> Collect Wiki lifecycle events

app/EventPageUpdate.php, app/Http/Controllers/Backend/QsController.php, app/QsBatch.php, database/factories/EventPageUpdateFactory.php, database/factories/QsBatchFactory.php, tests/Routes/QsBatch/QsControllerTest.php
Ticket https://phabricator.wikimedia.org/T333164
=> Adjust QueryService updater batch order

routes/api.php, routes/backend.php, routes/general.php, routes/sandbox.php
Just a small fix for the correct router class that is used, so you can make use of it in your IDE.
=> fix(routes): router class annotation

CHANGELOG.md, app/Console/Kernel.php
Ticket https://phabricator.wikimedia.org/T348256
=> chore(qs): temporarily disable job

CHANGELOG.md, app/Console/Kernel.php
Ticket https://phabricator.wikimedia.org/T348256
This should be deployed _after_ applying the migrations from #689 and updating the QsCheckpoint
=> chore(qs): re-enable job

CHANGELOG.md, start.sh
Ticket https://phabricator.wikimedia.org/T352662
This change is backwards compatible and could be deployed without any additional chart changes.
=> feat: Allow passing a queue name to the worker

CHANGELOG.md, app/Console/Commands/RebuildQueryserviceData.php
Ticket: https://phabricator.wikimedia.org/T352662
Connects https://github.com/wmde/wbaas-deploy/pull/1322
=> feat: Dispatch jobs for rebuilding Queryservice data to non-default queue

CHANGELOG.md, app/Jobs/DeleteWikiFinalizeJob.php, app/Jobs/SetWikiLogo.php, composer.json, composer.lock, config/filesystems.php, tests/Jobs/DeleteWikiDispatcherJobTest.php, tests/Jobs/DeleteWikiFinalizeJobTest.php, tests/Jobs/SetWikiLogoTest.php, tests/Routes/Wiki/LogoUpdateTest.php
Ticket https://phabricator.wikimedia.org/T354744
=> feat: use s3 driver for storing files in gcp bucket

CHANGELOG.md, app/Jobs/DeleteWikiFinalizeJob.php, app/Jobs/SetWikiLogo.php, composer.json, composer.lock, config/filesystems.php, tests/Jobs/DeleteWikiDispatcherJobTest.php, tests/Jobs/DeleteWikiFinalizeJobTest.php, tests/Jobs/SetWikiLogoTest.php, tests/Routes/Wiki/LogoUpdateTest.php
=> Revert "feat: use s3 driver for storing files in gcp bucket"

CHANGELOG.md, app/Wiki.php, tests/Routes/Wiki/DetailsTest.php
Ticket https://phabricator.wikimedia.org/T354954
=> fix(wiki-settings): include questy settings in details

CHANGELOG.md
includes https://github.com/wbstack/api/pull/721
=> Release 8x.35.0

CHANGELOG.md
This reverts commit 2b0657d8cb953cc2c3affe24a7a7b943be29d8c9.
=> Revert "update CHANGELOG.md"

app/User.php, app/Wiki.php, database/migrations/2024_05_15_042959_add_admin_role_to_users.php, database/migrations/2024_05_15_043447_add_wiki_deletion_reason.php
https://phabricator.wikimedia.org/T347865
The admins here are WMDE wikibase cloud team
=> Add user admin flag and deletion reasons to the DB

resources/views/vendor/mail/html/message.blade.php, resources/views/vendor/mail/text/message.blade.php, resources/views/vendor/notifications/email.blade.php
=> Fix: Change email signature

app/Notifications/EmptyWikiNotification.php
=> Update Getting Started url link in empty wiki email

CHANGELOG.md
=> Changelog 10x.18.7

CHANGELOG.md
includes https://github.com/wbstack/api/pull/918/files
=> Release 10x.19.0
